# Generated by Django 5.0.6 on 2024-10-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_proba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proba',
        ),
    ]
